#use_frameworks!

platform :ios, '8.0'

target 'HoloCollectionView_Example' do
  pod 'HoloCollectionView', :path => '../'

  target 'HoloCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
